apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployme
  template:
    metadata:
      labels:
        app: deployme
    spec:
      containers:
      - name: deployme
        image: deployme
        imagePullPolicy: Never
        ports:
        - containerPort: 3000