apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployme
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: deployme.loc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deployme
                port:
                  number: 3000